version: '3'

services:
  tydom2mqtt:
    build: ./
    container_name: tydom2mqtt
    environment:
        - ${TYDOM_MAC}
        - ${TYDOM_PASSWORD}
        - ${TYDOM_IP}
        - ${MQTT_HOST}
        - ${MQTT_PORT}
        - ${MQTT_USER}
        - ${MQTT_PASSWORD}