version: '3'

services:
  tydom2mqtt:
    build: ./
    container_name: tydom2mqtt
    environment:
      - TYDOM_MAC=${TYDOM_MAC}
      - TYDOM_PASSWORD=${TYDOM_PASSWORD}
      - TYDOM_IP=${TYDOM_IP}
      #- TYDOM_ALARM_PIN = None
      #- TYDOM_ALARM_HOME_ZONE = 1
      #- TYDOM_ALARM_NIGHT_ZONE = 2
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      #- MQTT_SSL=false