version: '3'

services:
  tydom2mqtt:
    build: ./
    container_name: tydom2mqtt
    environment:
      - TYDOM_MAC=001A25FFFFFF
      - TYDOM_PASSWORD=MyTydomSuperStrongPassword
      - TYDOM_IP=mediation.tydom.com          # or local IP address like 192.168.1.33
      #- TYDOM_ALARM_PIN = None
      #- TYDOM_ALARM_HOME_ZONE = 1
      #- TYDOM_ALARM_NIGHT_ZONE = 2
      - MQTT_HOST=localhost                   # or local IP address like 192.168.58.8
      - MQTT_PORT=1883
      #- MQTT_USER=admin
      #- MQTT_PASSWORD=MyMQTTSuperStrongPassword
      #- MQTT_SSL=false